[build]
  base = "/"
  publish = ".next"
  command = "npm run build"
  functions = "/netlify"

[build.environment]
  NEXT_SERVERLESS = "true"
  SANITY_PROJECT_ID="o3vixnje"
  SANITY_DATASET="production"
  SANITY_TOKEN="sknF6H9ecAzPLGGDQlI6OtyNFaGTGDjY7XGJ9X3GMShGOthfKeGvEKRuHisfIgOEGwll5bRWmowtX6rAhhTx2SoxatoT43lM14IobUYUbd1cUtAkjRuzxKFA71W8qiMc3Awv2oiR2gw2Yky2foI4kNVvNi6hwDAj5VB6PoVLg7zugX6nQR54"
  BUILD_LANGUAGES = "en-US,it-IT"
  BUILD_CMS = "sanity"
  CL_CLIENT_ID = "OjreBtCoC9NsGgul6YGKo4E4evSolJz533HMP7vOdh0"
  CL_ENDPOINT = "https://headless.commercelayer.io"
 
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-inline-functions-env"
  [plugins.inputs]
    buildEvent = "onBuild"

